//! UUID-based newtype identifiers for assets, materials, nodes, and scripts.
//!
//! Each identifier is a transparent wrapper around [`Uuid`] generated by the
//! [`define_id!`] macro. They are `Copy`, hashable, and serialize as plain UUID
//! strings so they can be used as map keys in JSON, TOML, etc.

use std::fmt;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

macro_rules! define_id {
    ($(#[$meta:meta])* $Name:ident) => {
        $(#[$meta])*
        #[derive(Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
        #[serde(transparent)]
        pub struct $Name(Uuid);

        impl $Name {
            /// Creates a new random identifier.
            #[inline]
            pub fn new() -> Self {
                Self(Uuid::new_v4())
            }

            /// Creates an identifier from an existing [`Uuid`].
            #[inline]
            pub fn from_uuid(uuid: Uuid) -> Self {
                Self(uuid)
            }

            /// Returns the inner [`Uuid`].
            #[inline]
            pub fn as_uuid(&self) -> &Uuid {
                &self.0
            }

            /// A nil (all-zeros) identifier, useful as a sentinel.
            pub const NIL: Self = Self(Uuid::nil());
        }

        impl Default for $Name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl fmt::Debug for $Name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}({})", stringify!($Name), self.0)
            }
        }

        impl fmt::Display for $Name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}", self.0)
            }
        }
    };
}

define_id!(
    /// Identifies a loaded or referenced asset (mesh, texture, etc.).
    AssetId
);

define_id!(
    /// Identifies a material definition.
    MaterialId
);

define_id!(
    /// Identifies a node in the scene graph.
    NodeId
);

define_id!(
    /// Identifies a script attached to an entity.
    ScriptId
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_are_unique() {
        let a = AssetId::new();
        let b = AssetId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn nil_is_consistent() {
        assert_eq!(MaterialId::NIL, MaterialId::from_uuid(Uuid::nil()));
    }

    #[test]
    fn serde_roundtrip() {
        let id = NodeId::new();
        let json = serde_json::to_string(&id).unwrap();
        let back: NodeId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, back);
    }
}
